sudo: required
services:
  - docker
language: node_js
node_js:
  - 16
cache:
  directories:
    - node_modules

before_install:
  - docker build -t estarguars113/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true estarguars113/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'aws-region'
  app: 'docker'
  env: 'docker-env'
  bucket_name: 'bucket-name'
  bucket_path: 'bucket-folder'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  